# Database Configuration (MySQL Workbench)
#db.url=jdbc:mysql://localhost:3306/buildtrack
db.url=jdbc:mysql://localhost:3306/buildtrack
db.username=root
db.password=12345
db.driver=com.mysql.cj.jdbc.Driver

# Email Configuration
SMTP_HOST=smtp.gmail.com

SMTP_PORT=465

SMTP_USER=sandeshdahal3547@gmail.com

SMTP_PASSWORD=odvfdyayfrshskgh

# SMTP_FROM is derived from SMTP_USER or set explicitly if you want
SMTP_FROM=BuildTrack <noreply@buildtrack.com>
