package com.buildtrack.util;

import com.buildtrack.model.Payslip;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

/**
 * Minimal PDF generator for simple text-only payslips.
 * This constructs a very small PDF (single page, Helvetica) without external libs.
 */
public class PdfUtil {

    public static byte[] generatePayslipPdf(Payslip p) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        // Build content stream (text)
        StringBuilder text = new StringBuilder();
        text.append("BT /F1 12 Tf 50 750 Td (");
        text.append(escape(p.getWorkerName() != null ? p.getWorkerName() : "Worker"));
        text.append(") Tj T* (Month: ");
        text.append(escape(p.getMonthYearDisplay() != null ? p.getMonthYearDisplay() : p.getMonthYear()));
        text.append(") T* (Total Days: ");
        text.append(p.getTotalDays());
        text.append(") T* (Half Days: ");
        text.append(p.getHalfDays());
        text.append(") T* (Daily Rate: ");
        text.append(p.getDailyWage() != null ? p.getDailyWage().toPlainString() : "0");
        text.append(") T* (Total Salary: ");
        text.append(p.getTotalSalary() != null ? p.getTotalSalary().toPlainString() : "0");
        text.append(") T* (Generated By: ");
        text.append(escape(p.getGeneratedByName() != null ? p.getGeneratedByName() : ""));
        text.append(") ET");

        byte[] contentBytes = text.toString().getBytes(StandardCharsets.US_ASCII);

        // Prepare PDF objects
        String header = "%PDF-1.4\n%âãÏÓ\n";

        // object 1: catalog
        String obj1 = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n";

        // object 2: pages
        String obj2 = "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n";

        // object 3: page
        String obj3 = "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n";

        // object 4: font
        String obj4 = "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n";

        // object 5: content stream
        String obj5Header = "5 0 obj\n<< /Length " + contentBytes.length + " >>\nstream\n";
        String obj5Footer = "\nendstream\nendobj\n";

        // Assemble PDF and track xref offsets
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        bos.write(header.getBytes(StandardCharsets.US_ASCII));

        int offset1 = bos.size();
        bos.write(obj1.getBytes(StandardCharsets.US_ASCII));

        int offset2 = bos.size();
        bos.write(obj2.getBytes(StandardCharsets.US_ASCII));

        int offset3 = bos.size();
        bos.write(obj3.getBytes(StandardCharsets.US_ASCII));

        int offset4 = bos.size();
        bos.write(obj4.getBytes(StandardCharsets.US_ASCII));

        int offset5 = bos.size();
        bos.write(obj5Header.getBytes(StandardCharsets.US_ASCII));
        bos.write(contentBytes);
        bos.write(obj5Footer.getBytes(StandardCharsets.US_ASCII));

        int xrefOffset = bos.size();

        // xref table
        StringBuilder xref = new StringBuilder();
        xref.append("xref\n0 6\n");
        xref.append(String.format("%010d 65535 f \n", 0));
        xref.append(String.format("%010d 00000 n \n", offset1));
        xref.append(String.format("%010d 00000 n \n", offset2));
        xref.append(String.format("%010d 00000 n \n", offset3));
        xref.append(String.format("%010d 00000 n \n", offset4));
        xref.append(String.format("%010d 00000 n \n", offset5));

        bos.write(xref.toString().getBytes(StandardCharsets.US_ASCII));

        // trailer
        String trailer = "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n" + xrefOffset + "\n%%EOF\n";
        bos.write(trailer.getBytes(StandardCharsets.US_ASCII));

        return bos.toByteArray();
    }

    private static String escape(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
    }
}
